#! /bin/bash

# Estimate the ground truth parameters from the full dataset for computing the MAPEs
python3 ground_truth.py

# Dataset generated by various GPT methods or ground truth
methods=("gpt-0613" "cot-gpt-0613" "gpt-0125" "cot-gpt-0125" "gpt-4" "cot-gpt-4" "gpt-4o" "cot-gpt-4o" "fs-gpt-4o" "ft-gpt-4o")


# AAE Estimators
for m in 50 100 150 200
do
    for method in "${methods[@]}"
    do
        python3 debias.py -nr $m -method $method -nt 50 -gm 'nn'
    done
done


# Naive Estimators

for m in 0 50 100 150 200
do
    for method in "${methods[@]}"
    do
        python3 naive.py -nr $m -method $method -nt 50
    done
done

# PPI-based Estimators
for m in 50 100 150 200
do
    for method in "${methods[@]}"
    do
        python3 ppi.py -nr $m -method $method -nt 50 -db 'ppi'
        python3 ppi.py -nr $m -method $method -nt 50 -db 'ppi++'
    done
done



# Additional experiments to get results for Table 4
python3 naive.py -nr 25 -method 'real' -nt 50 -nma 250 -sa 25